spring:
  datasource:
      url: jdbc:mysql://106.13.40.231:3306/Lift?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: j8787667n
      driver-class-name: com.mysql.cj.jdbc.Driver