spring:
  datasource:
    url: jdbc:mysql://106.13.40.231:3306/Lift?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: j8787667n
    driver-class-name: com.mysql.jdbc.Driver





    #时间格式统一返回
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #如果使用字符串表示，用这行设置格式
    timezone: GMT+8
    serialization:
      write-dates-as-timestamps: false



mybatis:
  type-aliases-package: com.gy.life.model
  mybatis-config-location: classpath*:mybatis/mybatis-config:xml
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helperDialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql
  #七牛
qiniu:
  AccessKey: "z1SeaQxN7yOXQ61Q1ZYkdXTnMwff4J2gAXS5lpCm"
  SecretKey: "dZr-3X0pxNFCYm3HRzv-weEn28IQlPKsumUxSauI"
  #七牛空间名
  Bucket: "life"
  #外链访问路径
  cdn:
    prefix: "pwz4hw6y3.bkt.clouddn.com"

#token验证
jwt:
  secret: "123343"
  #服务端接口配置
#server:
#  port: 8084
#  servlet:
#    context-path: /api
oauth:
  wx:
    appId: "wx106cd96d636d6e1a"
    secret: "212178ab5e65e29f91ae13a3e5ef1d3f"
logging:
  config: classpath:logback-spring.xml
  debug: true
  level: info
